FROM python:3.11-slim

WORKDIR /app

# Poetry のインストール
RUN pip install poetry

# 依存関係のインストール
COPY ./pyproject.toml ./poetry.lock* /app/
RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi

# アプリケーションコードのコピー
COPY . /app/

# 環境変数の設定
ENV PYTHONPATH=/app
ENV TESTING=True

# テスト実行コマンド
CMD ["pytest", "-v"]
