version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
    environment:
      - TESTING=True
      - DATABASE_URL=sqlite:///:memory:
      - SECRET_KEY=test_secret_key
      - FIREBASE_CREDENTIALS_PATH=/app/tests/mocks/firebase_credentials.json
      - FIREBASE_API_KEY=test_api_key
      - S3_BUCKET_NAME=test-bucket
      - S3_REGION=ap-northeast-1
      - STRIPE_API_KEY=test_stripe_key
      - STRIPE_WEBHOOK_SECRET=test_webhook_secret
